name: user_list_app
description: "Mobile app for showcasing user list, details, offline features."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.7
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  go_router: ^17.0.0
  get_it: ^9.0.5
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: fontRegular
      fonts:
        - asset: assets/font/fontRegular.ttf
    - family: fontBold
      fonts:
        - asset: assets/font/fontBold.ttf
